---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: hyperdisk-balanced
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-balanced
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: 'postgres:14'  # PostgreSQL image version (adjust as needed)
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432  # PostgreSQL default port
        env:
        - name: POSTGRES_USER
          value: "postgres"  # Replace with your database user
        - name: POSTGRES_PASSWORD
          value: "password"  # Replace with your password
        - name: POSTGRES_DB
          value: ps_db
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data2  
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: my-pvc  
